FROM node:22-bookworm-slim

WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm ci

WORKDIR /app
COPY shared ./shared
COPY backend ./backend

EXPOSE 3001
WORKDIR /app/backend
CMD ["node", "--watch", "server.js"]
