FROM node:22-bookworm-slim

WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm ci

WORKDIR /app
COPY shared ./shared
COPY backend ./backend

EXPOSE 3001
WORKDIR /app/backend
CMD ["./node_modules/.bin/nodemon", "--legacy-watch", "--watch", "/app/backend", "--watch", "/app/shared", "--ignore", "/app/backend/node_modules", "--ext", "js,cjs,json", "server.js"]
